M48
; DRILL file {KiCad 9.0.0} date 2025-03-26T12:10:22+1100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-26T12:10:22+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0827
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X0.6801Y-1.3424
X1.8238Y-1.3424
X2.9675Y-1.3424
X4.1112Y-1.3424
T2
X0.156Y-0.166
X4.315Y-0.166
M30
